server:
  port: 10001 # 服务运行端口

spring:
  application:
    name: eureka-server1 # 服务名称
eureka:
  instance:
    hostname: server1 # 指定主机地址
  client:
    fetch-registry: true # 指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true # 指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
      defaultZone: http://server2:10002/eureka/ #注册到另一个Eureka注册中心